name: Publish to npm

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v' (e.g., v1.0.0, v2.3.1)

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Publish to npm
      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 5: Get version from the tag
      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Step 6: Generate changelog from CHANGELOG.md
      - name: Extract Changelog Entry
        id: changelog
        run: |
          VERSION=${{ env.VERSION }}
          VERSION=${VERSION#refs/tags/}
          VERSION=${VERSION#v}
          
          # Use awk to extract just the message content for the version
          CHANGELOG_ENTRY=$(awk -v version="[$VERSION]" '
            BEGIN {found=0; printing=0}
            $0 ~ "^## " version {found=1; next}
            found && $0 ~ "^### " {printing=1; next}
            found && $0 ~ "^##" {exit}
            found && printing && $0 ~ "^- " {
              # Remove the leading "- " and print the message
              print substr($0, 3)
              exit
            }
          ' CHANGELOG.md)

          # If no entry is found, use a fallback message
          if [ -z "$CHANGELOG_ENTRY" ]; then
            CHANGELOG="No changes in this release."
          else
            CHANGELOG="$CHANGELOG_ENTRY"
          fi
          
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV

      # Step 7: Debugging: Print the extracted changelog
      - name: Debug Extracted Changelog
        run: |
          echo "Extracted Changelog for version ${{ env.VERSION }}: ${{ env.CHANGELOG }}"

      # Step 8: Create Release with the Changelog
      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}  # Tag name is used as the version
          release_name: ${{ github.ref }}  # Release name based on the tag
          body: |
            ## What's Changed:
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false

